
const btn0 = document.querySelector('.chev');
btn0.addEventListener('click', () => {
  btn0.classList.toggle('rotate');
});

const btn = document.querySelector('.chev1');
btn.addEventListener('click', () => {
  btn.classList.toggle('rotate');



  // $(document).ready(function () {
  //   var selectAllCheckBox = $(".checkAll");
  // });

  // selectAllCheckBox.on("change", function () {
  //   var isChecked = $(this).prop("checked");

  //   var checkedboxes = $("input[type='checkbox']").not(this);

  //   checkedboxes.prop("checked", isChecked);

  // });
});